title: "🚧※執筆中 【フロントエンド✕TDD】実際にやってみた🚧"
summary: "フロントエンドでTDDってできるの？どんな進め方になるの？実際やってみるとどうなの？その謎を解くため、我々特捜班はジャングルの奥地へと向かった…\n\n
フロントエンドのTDD実践については賛否両論あったり、具体的な理解度を上げようとサンプルを探しても、\n
単純な実装はあるけど、実際のプロダクト開発のような中で実践する例が見つかリませんでした。\n\n
そこで、実践のチュートリアルをステップバイステップで進めるサンプル本を作ってみました。\n
実際にフロントエンドでTDDをしながら進めるとどうなるか、実際にやってみて勧めてきた記録をチュートリアル的にまとめたものです。
"
topics: ["React", "テスト", "TDD", "フロントエンド"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - example1
  - example2
  - example3
  - example4
  - example5
  - example6
  - example7
  - example8
  - continue
