title: "AIで誰もがサービスを作れる世界の夢を見るか？"
summary: "GitHub Copilot/ChatGPTを使ったサービス開発"
topics: ["GitHub Copilot", "AI", "ChatGPT"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
  - example3
  # - example4
  # - example5
  # - example6
  # - example7
  # - example8
  # - example9
  - example_emplty
